# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "defe5dd0f037b49d15c2cb306f8e1666"
name = "my-alert-first-app-v0"
handle = "my-alert-first-app-v0"
application_url = "https://alert-app.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "my-first-developmental-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://alert-app.fly.dev/auth/callback",
  "https://alert-app.fly.dev/auth/shopify/callback",
  "https://alert-app.fly.dev/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
