# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7e8af0bc91504436e7567f4eed0636f5"
name = "my-alert-first-app-v0"
handle = "my-alert-first-app-v0"
application_url = "https://covering-airfare-attempted-basic.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "my-first-developmental-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://covering-airfare-attempted-basic.trycloudflare.com/auth/callback",
  "https://covering-airfare-attempted-basic.trycloudflare.com/auth/shopify/callback",
  "https://covering-airfare-attempted-basic.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
